"""your migration message

Revision ID: a6860ae739ff
Revises: 790e6a06828c
Create Date: 2025-03-17 19:35:52.051805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlalchemy.dialects.postgresql import ENUM
from lingreelsai.models import ClipLengthEnum 

# revision identifiers, used by Alembic.
revision: str = 'a6860ae739ff'
down_revision: Union[str, None] = '790e6a06828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE cliplengthenum AS ENUM ('short', 'medium', 'long');")
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_keywords',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('clip_id', 'keyword_id')
    )
    op.create_table('emoji_overlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('estimated_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('track_url', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_overlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('font', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('transition_type', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('captions', sa.Column('text', sa.String(), nullable=False))
    op.add_column('captions', sa.Column('start_time', sa.Float(), nullable=True))
    op.add_column('captions', sa.Column('end_time', sa.Float(), nullable=True))
    op.add_column('captions', sa.Column('position', sa.String(), nullable=True))
    op.drop_index('ix_captions_id', table_name='captions')
    op.drop_column('captions', 'language')
    op.drop_column('captions', 'caption_text')
    op.add_column('clips', sa.Column('title', sa.String(), nullable=True))
    op.add_column('clips', sa.Column('description', sa.String(), nullable=True))
    op.add_column('clips', sa.Column('virality_score', sa.Float(), nullable=True))
    op.add_column('clips', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('clips', sa.Column('preferred_clip_length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='cliplengthenum'), nullable=True))
    op.drop_column('clips', 'engagement_score')
    op.add_column('videos', sa.Column('file_path', sa.String(), nullable=True))
    op.alter_column('videos', 'video_length',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'video_length',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('videos', 'file_path')
    op.add_column('clips', sa.Column('engagement_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('clips', 'preferred_clip_length')
    op.drop_column('clips', 'thumbnail')
    op.drop_column('clips', 'virality_score')
    op.drop_column('clips', 'description')
    op.drop_column('clips', 'title')
    op.drop_column('clips', 'preferred_clip_length')
    op.execute("DROP TYPE IF EXISTS cliplengthenum")
    op.add_column('captions', sa.Column('caption_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('captions', sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_captions_id', 'captions', ['id'], unique=False)
    op.drop_column('captions', 'position')
    op.drop_column('captions', 'end_time')
    op.drop_column('captions', 'start_time')
    op.drop_column('captions', 'text')
    op.drop_table('transitions')
    op.drop_table('text_overlays')
    op.drop_table('music_tracks')
    op.drop_table('jobs')
    op.drop_table('emoji_overlays')
    op.drop_table('clip_keywords')
    op.drop_table('template_presets')
    op.drop_table('notifications')
    op.drop_table('keywords')
    
    # ### end Alembic commands ###
